"""user relationship

Revision ID: 04ba8cef0fc4
Revises: 51981bff6657
Create Date: 2025-05-01 20:54:05.052946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ba8cef0fc4'
down_revision: Union[str, None] = '51981bff6657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canvastoken', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'canvastoken', ['user_id'])
    op.create_foreign_key(None, 'canvastoken', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'canvastoken', type_='foreignkey')
    op.drop_constraint(None, 'canvastoken', type_='unique')
    op.drop_column('canvastoken', 'user_id')
    # ### end Alembic commands ###
